numpy:
  - 2
libprotobuf:
  - 6.31.1
protobuf:
  - 6.31.1
spdlog:
  - 1.15
pugixml:
  - '1.15'
libopencv:
  - 4.12.0
libxml2:
  - 2.13.*
graphviz:
  - 13.*
vtk:
  - 9.5.1
pcl:
  - 1.15.1
ffmpeg:
  - 8

# Workaround for https://github.com/RoboStack/ros-kilted/pull/40#issuecomment-2782226697
cmake:
  - 3.*

cdt_name:  # [linux]
  - conda  # [linux]

python:
  - 3.12.* *_cpython
python_impl:
  - cpython

c_compiler:
  - gcc                        # [linux]
  - clang                      # [osx]
  - vs2022                     # [win]
c_compiler_version:            # [unix]
  - 13                         # [linux]
  - 18                         # [osx]
c_stdlib:
  - sysroot                    # [linux]
  - macosx_deployment_target   # [osx]
  - vs                         # [win]
c_stdlib_version:              # [unix]
  - 2.17                       # [linux]
  - 10.13                      # [osx and x86_64]
  - 11.0                       # [osx and arm64]
cxx_compiler:
  - gxx                        # [linux]
  - clangxx                    # [osx]
  - vs2022                     # [win]
cxx_compiler_version:          # [unix]
  - 13                         # [linux]
  - 18                         # [osx]

libzenohc:
  - 1.5.1
libzenohcxx:
  - 1.5.1
libcap:
  - 2.75
